name: afarinick_forms
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path_provider: any
  flutter_slidable: any
  http: any
  google_fonts: ^4.0.1
  animated_icon_button: any
  uuid: any
  intl: any
  equatable: any
  lottie:
  flutter_bloc: any
  back_pressed:
  connectivity:
  data_connection_checker_nulls: ^0.0.2
  flutter_easyloading:
  shared_preferences: ^2.2.2
  cupertino_icons: any
  animate_do:

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/Kumad_Global.png
    - assets/images/background.png
    - assets/images/icon.webp

  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/Product-Sans-Bold.ttf
        - asset: fonts/Product-Sans-Bold-Italic.ttf
          style: italic
        - asset: fonts/Product-Sans-Italic.ttf
        - asset: fonts/Product-Sans-Regular.ttf
    - family: Catull
      fonts:
        - asset: fonts/Catull.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
